version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./:/app
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]